#!/bin/sh

########################################################################################
#
# This script sends DAGs over to the GCS bucket of the target Composer environment
# Google.com
#
#######################################################################################

# Stop the script in case of any error
set -e

# Initialize settings
MYDIR=$(pwd)
CONFIG_FOLDER=${MYDIR}"/config"

. ${CONFIG_FOLDER}/env.cfg

# Retrieve target Composer environment settings: Storage bucket for DAG deployment
bucket=$(gcloud composer environments describe ${ENVIRONMENT} --location=${REGION} --format="value(config.dagGcsPrefix)")

# Iterate through all DAG files and send them to the target bucket 
for filepath in ${DAGFOLDER}/*.py; do
    gsutil cp ${filepath} ${bucket}
done

echo "Your DAGs were transferred successfully.\n"
echo "!IMPORTANT!"
echo "You may need to add Environment Variables and PyPi packages from this environment (from config/variables.cfg and configs/pypi.cfg) to your Composer instance."
echo "This step is not performed automatically as it may result in conflicts."
